# Generated by Django 5.2.9 on 2025-12-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_description_product_bridge_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
